import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#0b0f10',
        'primary': '#d2bbff',
        'tertiary': '#bec6e0',
        'error-container': '#93000a',
        'outline-variant': '#4a4455',
        'on-secondary-fixed-variant': '#003ea8',
        'tertiary-fixed-dim': '#bec6e0',
        'on-primary': '#3f008e',
        'on-secondary-container': '#cdd7ff',
        'surface-container-low': '#191c1e',
        'on-error': '#690005',
        'tertiary-fixed': '#dae2fd',
        'error': '#ffb4ab',
        'surface-container-highest': '#323537',
        'surface-variant': '#323537',
        'on-tertiary-container': '#dee5ff',
        'secondary-fixed': '#dbe1ff',
        'inverse-surface': '#e0e3e5',
        'on-surface-variant': '#ccc3d8',
        'surface-tint': '#d2bbff',
        'on-tertiary': '#283044',
        'on-primary-fixed': '#25005a',
        'on-secondary': '#002a78',
        'secondary': '#b4c5ff',
        'surface-container-high': '#272a2c',
        'background': '#101415',
        'inverse-on-surface': '#2d3133',
        'outline': '#958da1',
        'on-primary-fixed-variant': '#5a00c6',
        'primary-container': '#7c3aed',
        'surface-bright': '#363a3b',
        'on-primary-container': '#ede0ff',
        'on-background': '#e0e3e5',
        'on-secondary-fixed': '#00174b',
        'tertiary-container': '#5e667d',
        'surface': '#101415',
        'inverse-primary': '#732ee4',
        'surface-dim': '#101415',
        'primary-fixed-dim': '#d2bbff',
        'on-surface': '#e0e3e5',
        'primary-fixed': '#eaddff',
        'on-tertiary-fixed-variant': '#3f465c',
        'secondary-fixed-dim': '#b4c5ff',
        'secondary-container': '#0053db',
        'on-tertiary-fixed': '#131b2e',
        'on-error-container': '#ffdad6',
        'surface-container': '#1d2022',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'container-max': '1280px',
        'md': '24px',
        'xs': '8px',
        'sm': '16px',
        'base': '4px',
        'lg': '40px',
        'xl': '64px',
        'gutter': '24px',
      },
      fontFamily: {
        'headline-md': ['var(--font-inter)', 'sans-serif'],
        'body-md': ['var(--font-inter)', 'sans-serif'],
        'label-sm': ['var(--font-inter)', 'sans-serif'],
        'display-lg-mobile': ['var(--font-inter)', 'sans-serif'],
        'code-mono': ['var(--font-jetbrains-mono)', 'monospace'],
        'body-lg': ['var(--font-inter)', 'sans-serif'],
        'display-lg': ['var(--font-inter)', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'code-mono': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
      },
    },
  },
  plugins: [],
}

export default config
